export 'package:disehos_one/widgets/background_triangle_bottom_widget.dart';
export 'package:disehos_one/widgets/background_triangle_widget.dart';
export 'package:disehos_one/widgets/header_circle_widget.dart';
export 'package:disehos_one/widgets/header_curve_top_widget.dart';
export 'package:disehos_one/widgets/header_diagonal_widget.dart';
export 'package:disehos_one/widgets/header_peak_widget.dart';
export 'package:disehos_one/widgets/header_square_widget.dart';
export 'package:disehos_one/widgets/header_waves_widget.dart';
export 'package:disehos_one/widgets/progress_indicator.dart';
